window.games = [
{id:1,name:"Grand Theft Auto V",platform:"PC",image:"images/gta5.jpg",description:"لعبة عالم مفتوح من Rockstar Games.",download:"https://www.rockstargames.com/gta-v"},
{id:2,name:"Red Dead Redemption 2",platform:"PC",image:"images/rdr2.jpg",description:"مغامرات الغرب الأمريكي.",download:"https://www.rockstargames.com/reddeadredemption2"},
{id:3,name:"Minecraft",platform:"PC",image:"images/minecraft.jpg",description:"لعبة البناء والاستكشاف الشهيرة.",download:"https://www.minecraft.net"},
{id:4,name:"Fortnite",platform:"PC",image:"images/fortnite.jpg",description:"باتل رويال مجانية.",download:"https://www.fortnite.com"},
{id:5,name:"Cyberpunk 2077",platform:"PC",image:"images/cyberpunk2077.jpg",description:"عالم مستقبلي مفتوح.",download:"https://www.cyberpunk.net"},
{id:6,name:"Elden Ring",platform:"PS5",image:"images/eldenring.jpg",description:"لعبة RPG ملحمية.",download:"https://en.bandainamcoent.eu/elden-ring"},
{id:7,name:"God of War Ragnarök",platform:"PS5",image:"images/gowr.jpg",description:"مغامرات كريتوس.",download:"https://www.playstation.com"},
{id:8,name:"Forza Horizon 5",platform:"Xbox",image:"images/forza5.jpg",description:"سباقات عالم مفتوح.",download:"https://forza.net"},
{id:9,name:"Call of Duty Warzone",platform:"PC",image:"images/warzone.jpg",description:"معارك جماعية حديثة.",download:"https://www.callofduty.com/warzone"},
{id:10,name:"Assassin's Creed Mirage",platform:"PS5",image:"images/acmirage.jpg",description:"مغامرة تاريخية.",download:"https://www.ubisoft.com"},
{id:11,name:"The Witcher 3",platform:"PC",image:"images/witcher3.jpg",description:"مغامرات جيرالت.",download:"https://www.thewitcher.com"},
{id:12,name:"EA Sports FC 26",platform:"PS5",image:"images/fc26.jpg",description:"محاكاة كرة القدم.",download:"https://www.ea.com"},
{id:13,name:"Resident Evil 4",platform:"PS5",image:"images/re4.jpg",description:"رعب وبقاء.",download:"https://www.capcom.com"},
{id:14,name:"Sea of Thieves",platform:"Xbox",image:"images/seaofthieves.jpg",description:"مغامرات القراصنة.",download:"https://www.seaofthieves.com"},
{id:15,name:"Rocket League",platform:"PC",image:"images/rocketleague.jpg",description:"سيارات وكرة قدم.",download:"https://www.rocketleague.com"},
{id:16,name:"Hogwarts Legacy",platform:"PS5",image:"images/hogwarts.jpg",description:"عالم هاري بوتر السحري.",download:"https://www.hogwartslegacy.com"},
{id:17,name:"Marvel's Spider-Man 2",platform:"PS5",image:"images/spiderman2.jpg",description:"مغامرات سبايدرمان.",download:"https://www.playstation.com"},
{id:18,name:"Ghost of Tsushima",platform:"PS5",image:"images/ghostoftsushima.jpg",description:"مغامرة ساموراي ملحمية.",download:"https://www.playstation.com"},
{id:19,name:"Dying Light 2",platform:"PC",image:"images/dyinglight2.jpg",description:"نجاة وأكشن.",download:"https://www.techland.net"},
{id:20,name:"Far Cry 6",platform:"PC",image:"images/farcry6.jpg",description:"أكشن وعالم مفتوح.",download:"https://www.ubisoft.com"},
{id:21,name:"Battlefield 2042",platform:"PC",image:"images/bf2042.jpg",description:"حروب حديثة.",download:"https://www.ea.com"},
{id:22,name:"Need for Speed Unbound",platform:"PC",image:"images/nfsunbound.jpg",description:"سباقات سيارات.",download:"https://www.ea.com"},
{id:23,name:"The Last of Us Part I",platform:"PS5",image:"images/tlou1.jpg",description:"قصة بقاء مؤثرة.",download:"https://www.playstation.com"},
{id:24,name:"Death Stranding",platform:"PS5",image:"images/deathstranding.jpg",description:"مغامرة فريدة.",download:"https://www.kojimaproductions.jp"},
{id:25,name:"Black Myth: Wukong",platform:"PC",image:"images/wukong.jpg",description:"أساطير صينية.",download:"https://www.heishenhua.com"},
{id:26,name:"Starfield",platform:"PC",image:"images/starfield.jpg",description:"استكشاف الفضاء.",download:"https://www.starfieldgame.com"},
{id:27,name:"Diablo IV",platform:"PC",image:"images/diablo4.jpg",description:"أكشن RPG مظلم.",download:"https://diablo4.blizzard.com"},
{id:28,name:"Horizon Forbidden West",platform:"PS5",image:"images/horizonfw.jpg",description:"عالم مستقبلي.",download:"https://www.playstation.com"},
{id:29,name:"Alan Wake 2",platform:"PC",image:"images/alanwake2.jpg",description:"رعب نفسي.",download:"https://www.alanwake.com"},
{id:30,name:"It Takes Two",platform:"PC",image:"images/ittakestwo.jpg",description:"لعبة تعاونية.",download:"https://www.ea.com"},
{id:31,name:"Mortal Kombat 1",platform:"PS5",image:"images/mk1.jpg",description:"قتال دموي.",download:"https://www.mortalkombat.com"},
{id:32,name:"Tekken 8",platform:"PS5",image:"images/tekken8.jpg",description:"لعبة قتال.",download:"https://www.bandainamcoent.com"},
{id:33,name:"Apex Legends",platform:"PC",image:"images/apex.jpg",description:"باتل رويال.",download:"https://www.ea.com"},
{id:34,name:"Valorant",platform:"PC",image:"images/valorant.jpg",description:"تصويب تكتيكي.",download:"https://playvalorant.com"},
{id:35,name:"Genshin Impact",platform:"PC",image:"images/genshin.jpg",description:"عالم أنمي.",download:"https://genshin.hoyoverse.com"},
{id:36,name:"Roblox",platform:"PC",image:"images/roblox.jpg",description:"منصة ألعاب.",download:"https://www.roblox.com"},
{id:37,name:"Terraria",platform:"PC",image:"images/terraria.jpg",description:"بناء واستكشاف.",download:"https://terraria.org"},
{id:38,name:"Subnautica",platform:"PC",image:"images/subnautica.jpg",description:"استكشاف المحيط.",download:"https://unknownworlds.com"},
{id:39,name:"ARK Survival Evolved",platform:"PC",image:"images/ark.jpg",description:"الديناصورات والبقاء.",download:"https://www.ark-survival.net"},
{id:40,name:"Stardew Valley",platform:"PC",image:"images/stardew.jpg",description:"مزرعة وحياة.",download:"https://www.stardewvalley.net"},
{id:41,name:"Watch Dogs Legion",platform:"PC",image:"images/watchdogs3.jpg",description:"اختراق.",download:"https://www.ubisoft.com"},
{id:42,name:"Hitman 3",platform:"PC",image:"images/hitman3.jpg",description:"اغتيالات سرية.",download:"https://www.ioi.dk"},
{id:43,name:"FIFA 24",platform:"PS5",image:"images/fifa24.jpg",description:"كرة قدم.",download:"https://www.ea.com"},
{id:44,name:"Nier Automata",platform:"PC",image:"images/nier.jpg",description:"قصة فلسفية.",download:"https://www.square-enix.com"},
{id:45,name:"DOOM Eternal",platform:"PC",image:"images/doom.jpg",description:"قتال شياطين.",download:"https://bethesda.net"},
{id:46,name:"Hades",platform:"PC",image:"images/hades.jpg",description:"روللايت أكشن.",download:"https://www.supergiantgames.com"},
{id:47,name:"Cuphead",platform:"PC",image:"images/cuphead.jpg",description:"ستايل كرتوني.",download:"https://www.cupheadgame.com"},
{id:48,name:"Among Us",platform:"PC",image:"images/amongus.jpg",description:"خيانة واكتشاف.",download:"https://www.innersloth.com"},
{id:49,name:"Payday 2",platform:"PC",image:"images/payday2.jpg",description:"سرقات جماعية.",download:"https://www.overkillsoftware.com"},
{id:50,name:"The Sims 4",platform:"PC",image:"images/sims4.jpg",description:"محاكاة حياة.",download:"https://www.ea.com"}
];